### ISSUE TITLE
fun fact: is.element() is the prefix form of %in%

### ISSUE THREAD

**Issue by tjmahr** [mikedecr/prefix#1]
```
> is.element
function (el, set) 
match(as.vector(el), as.vector(set), 0L) > 0L
<bytecode: 0x000001da83961738>
<environment: namespace:base>

> `%in%`
function (x, table) 
match(x, table, nomatch = 0L) > 0L
<bytecode: 0x000001daf7660900>
<environment: namespace:base>
```

**Comment by mikedecr** [comment]
TIL! will debate whether to keep it. Wouldn't be shocked if there are other examples that I've duplicated

**Comment by mikedecr** [comment]
Upon reflection I think I will keep `isin`! There are two main reasons why.

1. Although `is.element` exists, the naming convention (the glaring `[.]`) creates some inconsistency with interface elsewhere in this package. The other functions I have not re-binded, namely `outer` and `kronecker`, are names that I probably would have picked anyway. I think a sensible rule going forward is to defer to a built-in function only if it feels sufficiently close to what this package would have included if the built-in function did not exist.
2. The definition you pasted for `is.element` is slightly different from `%in%`, and although it may not matter in nearly all cases, I think having the function emulate the operator exactly is safer (for now at least).

**Comment by tjmahr** [comment]
that's cool. i mostly just wanted to advertise it. just like how `getElement()` provides a prefix-version of `[[` and `@` or how `stats::setNames()` covers `names<-`. (Damn, even just a list of built-in prefix-alternatives would be helpful.)

Besides, it's probably easier for someone who knows what this package is about to grok `prefix::isin()` than the unfamiliar `is.element()`

**Comment by mikedecr** [comment]
For sure I getcha, I appreciate the advertisements. There are a lot of deepdown things about R that aren't popularly used, so any opportunity to learn about them is great. (And I've always been a fan of an explicit setNames + return than assigning into names)
